# Generated by Django 4.2 on 2023-05-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
