# Generated by Django 4.2.1 on 2023-05-05 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^T\\d{3}$', code='invalid_id_taller', message='El ID del taller debe tener el formato T001')])),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_nombre_taller', message='El nombre de taller debe tener solo numeros y letras', regex='^[a-zA-Z0-9]+$')])),
                ('id_direccion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='El número de teléfono debe tener el formato +1234567890 y contener de 9 a 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('id_sucursal', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^S\\d{3}$', code='invalid_id_sucursal', message='El ID de sucursal debe tener el formato S001')])),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('cant_tecnicos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)])),
            ],
        ),
        migrations.CreateModel(
            name='Turno_taller',
            fields=[
                ('id_turno', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('tipo', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('tecnico_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('patente', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField(max_length=30)),
                ('hora_inicio', models.TimeField(max_length=30)),
                ('fecha_fin', models.DateField(max_length=30)),
                ('hora_fin', models.TimeField(max_length=30)),
                ('papeles_en_regla', models.BooleanField(default=False)),
                ('taller_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.taller')),
            ],
        ),
    ]
