# Generated by Django 4.2.1 on 2023-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_turno_taller_id_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno_taller',
            name='tipo',
            field=models.CharField(choices=[('service', 'Service'), ('evaluacion', 'Evaluacion'), ('extraordinacio', 'Extraordinario')], max_length=14),
        ),
    ]
