# Generated by Django 4.2.1 on 2023-05-06 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_turno_taller_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno_taller',
            name='estado',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='fecha_fin',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='fecha_inicio',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='hora_fin',
            field=models.TimeField(max_length=8),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='hora_inicio',
            field=models.TimeField(max_length=8),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='id_turno',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='patente',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^(([A-Z]{2}\\d{3}[A-Z]{2})|([A-Z]{3}\\d{3}))$', code='invalid_patente', message='La patente ingresada no es valida. Debe ser en mayusculas con el formato 00AAA00 o ')]),
        ),
    ]
