# Generated by Django 4.2.1 on 2023-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_turno_taller_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno_taller',
            name='estado',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=10),
        ),
    ]
