# Generated by Django 4.2.1 on 2023-05-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_turno_taller_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno_taller',
            name='tipo',
            field=models.CharField(choices=[('service', 'Service'), ('evaluacion', 'Evaluacion'), ('extraordinario', 'Extraordinario')], max_length=14),
        ),
    ]
