# Generated by Django 4.2.1 on 2023-05-09 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_turno_taller_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno_taller',
            name='frecuencia_km',
            field=models.IntegerField(choices=[(5000, '5000'), (10000, '10000'), (15000, '15000'), (20000, '20000'), (25000, '25000'), (30000, '30000'), (35000, '35000'), (40000, '40000'), (45000, '45000'), (50000, '50000'), (55000, '55000'), (60000, '60000'), (65000, '65000'), (70000, '70000'), (75000, '75000'), (80000, '80000'), (85000, '85000'), (90000, '90000'), (95000, '95000'), (100000, '100000'), (105000, '105000'), (110000, '110000'), (115000, '115000'), (120000, '120000'), (125000, '125000'), (130000, '130000'), (135000, '135000'), (140000, '140000'), (145000, '145000'), (150000, '150000'), (155000, '155000'), (160000, '160000'), (165000, '165000'), (170000, '170000'), (175000, '175000'), (180000, '180000'), (185000, '185000'), (190000, '190000'), (195000, '195000'), (200000, '200000')], null=True, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(200000)]),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='id_turno',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='tipo',
            field=models.CharField(choices=[('service', 'Service'), ('evaluacion', 'Evaluacion'), ('extraordinario', 'Extraordinario'), ('reparacion', 'Reparacion')], max_length=14),
        ),
    ]
