# Generated by Django 4.2.1 on 2023-05-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_turno_taller_tecnico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno_taller',
            name='estado',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='tipo',
            field=models.CharField(choices=[('service', 'Service'), ('evaluacion', 'Evaluacion'), ('extraordinario', 'Extraordinario'), ('reparacion', 'Reparacion')], max_length=14, null=True),
        ),
    ]
