# Generated by Django 4.2.1 on 2023-05-11 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_alter_turno_taller_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno_taller',
            name='id_turno',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
