# Generated by Django 4.2 on 2023-04-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id_empleado', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=1)),
            ],
        ),
    ]
